import '../../domain/entities/ai_reasoning.dart';
import '../../domain/entities/exercise_difficulty.dart';

/// Training goal for program generation
enum TrainingGoal {
  strength('strength', 'Strength', '근력 향상'),
  hypertrophy('hypertrophy', 'Muscle Building', '근비대'),
  endurance('endurance', 'Endurance', '근지구력'),
  weightLoss('weight_loss', 'Weight Loss', '체중 감량'),
  generalFitness('general_fitness', 'General Fitness', '전반적 체력'),
  rehabilitation('rehabilitation', 'Rehabilitation', '재활'),
  athletic('athletic', 'Athletic Performance', '운동 능력');

  final String id;
  final String name;
  final String nameKo;

  const TrainingGoal(this.id, this.name, this.nameKo);

  String get displayName => nameKo;

  static TrainingGoal fromString(String value) {
    return TrainingGoal.values.firstWhere(
      (g) => g.id == value,
      orElse: () => TrainingGoal.generalFitness,
    );
  }
}

/// Program status
enum ProgramStatus {
  draft('draft', 'Draft', '초안'),
  active('active', 'Active', '활성'),
  completed('completed', 'Completed', '완료'),
  archived('archived', 'Archived', '보관');

  final String id;
  final String name;
  final String nameKo;

  const ProgramStatus(this.id, this.name, this.nameKo);

  String get displayName => nameKo;

  static ProgramStatus fromString(String value) {
    return ProgramStatus.values.firstWhere(
      (s) => s.id == value,
      orElse: () => ProgramStatus.draft,
    );
  }
}

/// A complete workout program generated by AI
class WorkoutProgramEntity {
  final String id;
  final String clientId;
  final String trainerId;
  final String name;
  final String? description;
  final TrainingGoal primaryGoal;
  final TrainingGoal? secondaryGoal;
  final int durationWeeks;
  final int sessionsPerWeek;
  final ProgramStatus status;
  final List<WorkoutDayEntity> workoutDays;
  final DateTime createdAt;
  final DateTime? startedAt;
  final DateTime? completedAt;
  final bool isAiGenerated;
  final int customizationCount; // Number of trainer modifications
  final String? aiModelVersion; // 'gpt-4o-mini' for AI, 'dart-fallback' for local generation

  const WorkoutProgramEntity({
    required this.id,
    required this.clientId,
    required this.trainerId,
    required this.name,
    this.description,
    required this.primaryGoal,
    this.secondaryGoal,
    required this.durationWeeks,
    required this.sessionsPerWeek,
    required this.status,
    required this.workoutDays,
    required this.createdAt,
    this.startedAt,
    this.completedAt,
    this.isAiGenerated = true,
    this.customizationCount = 0,
    this.aiModelVersion,
  });

  /// Check if program has been customized by trainer
  bool get isCustomized => customizationCount > 0;

  /// Get total exercises in program
  int get totalExercises =>
      workoutDays.fold(0, (sum, day) => sum + day.exercises.length);

  WorkoutProgramEntity copyWith({
    String? id,
    String? clientId,
    String? trainerId,
    String? name,
    String? description,
    TrainingGoal? primaryGoal,
    TrainingGoal? secondaryGoal,
    int? durationWeeks,
    int? sessionsPerWeek,
    ProgramStatus? status,
    List<WorkoutDayEntity>? workoutDays,
    DateTime? createdAt,
    DateTime? startedAt,
    DateTime? completedAt,
    bool? isAiGenerated,
    int? customizationCount,
    String? aiModelVersion,
  }) {
    return WorkoutProgramEntity(
      id: id ?? this.id,
      clientId: clientId ?? this.clientId,
      trainerId: trainerId ?? this.trainerId,
      name: name ?? this.name,
      description: description ?? this.description,
      primaryGoal: primaryGoal ?? this.primaryGoal,
      secondaryGoal: secondaryGoal ?? this.secondaryGoal,
      durationWeeks: durationWeeks ?? this.durationWeeks,
      sessionsPerWeek: sessionsPerWeek ?? this.sessionsPerWeek,
      status: status ?? this.status,
      workoutDays: workoutDays ?? this.workoutDays,
      createdAt: createdAt ?? this.createdAt,
      startedAt: startedAt ?? this.startedAt,
      completedAt: completedAt ?? this.completedAt,
      isAiGenerated: isAiGenerated ?? this.isAiGenerated,
      customizationCount: customizationCount ?? this.customizationCount,
      aiModelVersion: aiModelVersion ?? this.aiModelVersion,
    );
  }
}

/// A single workout day in a program
class WorkoutDayEntity {
  final String id;
  final String programId;
  final int dayNumber; // 1, 2, 3, etc.
  final String name; // "Day 1: Upper Body", "Push Day", etc.
  final String? focusArea;
  final List<ProgramExerciseEntity> exercises;
  final int estimatedDurationMinutes;

  const WorkoutDayEntity({
    required this.id,
    required this.programId,
    required this.dayNumber,
    required this.name,
    this.focusArea,
    required this.exercises,
    required this.estimatedDurationMinutes,
  });

  WorkoutDayEntity copyWith({
    String? id,
    String? programId,
    int? dayNumber,
    String? name,
    String? focusArea,
    List<ProgramExerciseEntity>? exercises,
    int? estimatedDurationMinutes,
  }) {
    return WorkoutDayEntity(
      id: id ?? this.id,
      programId: programId ?? this.programId,
      dayNumber: dayNumber ?? this.dayNumber,
      name: name ?? this.name,
      focusArea: focusArea ?? this.focusArea,
      exercises: exercises ?? this.exercises,
      estimatedDurationMinutes:
          estimatedDurationMinutes ?? this.estimatedDurationMinutes,
    );
  }
}

/// An exercise within a program day with AI reasoning
class ProgramExerciseEntity {
  final String id;
  final String workoutDayId;
  final String exerciseId;
  final String exerciseName;
  final String? exerciseNameKo;
  final int orderIndex;
  final int targetSets;
  final String targetReps; // "8-12" or "10" or "AMRAP"
  final double? targetWeight;
  final int? targetRpe; // Rate of perceived exertion 1-10
  final int restSeconds;
  final String? notes;
  final AIExerciseReasoning? aiReasoning;
  final List<ExerciseAlternative> alternatives;
  final String? originalExerciseId; // If swapped, reference to original
  final bool isSwapped;

  const ProgramExerciseEntity({
    required this.id,
    required this.workoutDayId,
    required this.exerciseId,
    required this.exerciseName,
    this.exerciseNameKo,
    required this.orderIndex,
    required this.targetSets,
    required this.targetReps,
    this.targetWeight,
    this.targetRpe,
    required this.restSeconds,
    this.notes,
    this.aiReasoning,
    this.alternatives = const [],
    this.originalExerciseId,
    this.isSwapped = false,
  });

  String get displayName => exerciseNameKo ?? exerciseName;

  ProgramExerciseEntity copyWith({
    String? id,
    String? workoutDayId,
    String? exerciseId,
    String? exerciseName,
    String? exerciseNameKo,
    int? orderIndex,
    int? targetSets,
    String? targetReps,
    double? targetWeight,
    int? targetRpe,
    int? restSeconds,
    String? notes,
    AIExerciseReasoning? aiReasoning,
    List<ExerciseAlternative>? alternatives,
    String? originalExerciseId,
    bool? isSwapped,
  }) {
    return ProgramExerciseEntity(
      id: id ?? this.id,
      workoutDayId: workoutDayId ?? this.workoutDayId,
      exerciseId: exerciseId ?? this.exerciseId,
      exerciseName: exerciseName ?? this.exerciseName,
      exerciseNameKo: exerciseNameKo ?? this.exerciseNameKo,
      orderIndex: orderIndex ?? this.orderIndex,
      targetSets: targetSets ?? this.targetSets,
      targetReps: targetReps ?? this.targetReps,
      targetWeight: targetWeight ?? this.targetWeight,
      targetRpe: targetRpe ?? this.targetRpe,
      restSeconds: restSeconds ?? this.restSeconds,
      notes: notes ?? this.notes,
      aiReasoning: aiReasoning ?? this.aiReasoning,
      alternatives: alternatives ?? this.alternatives,
      originalExerciseId: originalExerciseId ?? this.originalExerciseId,
      isSwapped: isSwapped ?? this.isSwapped,
    );
  }
}

/// An alternative exercise option
class ExerciseAlternative {
  final String exerciseId;
  final String exerciseName;
  final String? exerciseNameKo;
  final AlternativeType type;
  final String reason;
  final String? reasonKo;
  final ExerciseDifficulty difficulty;
  final EquipmentType equipment;

  const ExerciseAlternative({
    required this.exerciseId,
    required this.exerciseName,
    this.exerciseNameKo,
    required this.type,
    required this.reason,
    this.reasonKo,
    required this.difficulty,
    required this.equipment,
  });

  String get displayName => exerciseNameKo ?? exerciseName;
  String get displayReason => reasonKo ?? reason;
}
