import '../../../../shared/models/user_role.dart';
import '../../domain/entities/user_entity.dart';

/// User data model for API/database operations
/// Maps to Supabase 'accounts' table
class UserModel {
  final String id;
  final String userId; // Links to auth.users.id
  final String email;
  final String? name;
  final String role;
  final String? phone;
  final String? profilePhotoUrl;
  final DateTime createdAt;
  final DateTime? lastLoginAt;
  final DateTime? updatedAt;
  final bool isActive;
  final bool profileComplete;

  const UserModel({
    required this.id,
    required this.userId,
    required this.email,
    this.name,
    required this.role,
    this.phone,
    this.profilePhotoUrl,
    required this.createdAt,
    this.lastLoginAt,
    this.updatedAt,
    this.isActive = true,
    this.profileComplete = false,
  });

  /// Create from JSON (Supabase accounts table response)
  factory UserModel.fromJson(Map<String, dynamic> json) {
    return UserModel(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      email: json['email'] as String,
      name: json['full_name'] as String?,
      role: json['role'] as String? ?? 'client',
      phone: json['phone'] as String?,
      profilePhotoUrl: json['avatar_url'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      lastLoginAt: json['last_login_at'] != null
          ? DateTime.parse(json['last_login_at'] as String)
          : null,
      updatedAt: json['updated_at'] != null
          ? DateTime.parse(json['updated_at'] as String)
          : null,
      isActive: json['is_active'] as bool? ?? true,
      profileComplete: json['profile_complete'] as bool? ?? false,
    );
  }

  /// Convert to JSON for API (insert/update)
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'user_id': userId,
      'email': email,
      'full_name': name,
      'role': role,
      'phone': phone,
      'avatar_url': profilePhotoUrl,
      'created_at': createdAt.toIso8601String(),
      'last_login_at': lastLoginAt?.toIso8601String(),
      'updated_at': updatedAt?.toIso8601String(),
      'is_active': isActive,
      'profile_complete': profileComplete,
    };
  }

  /// Convert to JSON for insert (without id, let DB generate)
  Map<String, dynamic> toInsertJson() {
    return {
      'user_id': userId,
      'email': email,
      'full_name': name,
      'role': role,
      'phone': phone,
      'avatar_url': profilePhotoUrl,
      'is_active': isActive,
      'profile_complete': profileComplete,
    };
  }

  /// Convert to domain entity
  UserEntity toEntity() {
    return UserEntity(
      id: userId, // Use userId (auth.users.id) as the entity id
      email: email,
      name: name,
      role: UserRole.fromString(role),
      phone: phone,
      profilePhotoUrl: profilePhotoUrl,
      createdAt: createdAt,
      lastLoginAt: lastLoginAt,
    );
  }

  /// Create from domain entity
  factory UserModel.fromEntity(UserEntity entity) {
    return UserModel(
      id: '', // Will be generated by DB
      userId: entity.id,
      email: entity.email,
      name: entity.name,
      role: entity.role.value,
      phone: entity.phone,
      profilePhotoUrl: entity.profilePhotoUrl,
      createdAt: entity.createdAt,
      lastLoginAt: entity.lastLoginAt,
    );
  }
}
