import 'exercise_entity.dart';
import '../../../ai_workout/domain/entities/workout_program.dart';

/// A complete generated session with exercises and metadata
/// Generated by rule-based algorithm (not LLM)
class GeneratedSession {
  /// Focus area for this session (e.g., 'upper', 'push', 'legs', 'full_body')
  final String focusArea;

  /// Training split used for generation
  final TrainingSplit trainingSplit;

  /// The generated exercises with prescriptions
  final List<GeneratedExercise> exercises;

  /// When this session was generated
  final DateTime generatedAt;

  /// Session description for display
  final String? sessionDescription;

  /// Session description in Korean
  final String? sessionDescriptionKo;

  const GeneratedSession({
    required this.focusArea,
    required this.trainingSplit,
    required this.exercises,
    required this.generatedAt,
    this.sessionDescription,
    this.sessionDescriptionKo,
  });

  /// Get display description (Korean preferred)
  String get displayDescription =>
      sessionDescriptionKo ?? sessionDescription ?? '';

  /// Get total exercise count
  int get exerciseCount => exercises.length;

  /// Convert to list of maps for session creation
  List<Map<String, dynamic>> toExerciseMaps() {
    return exercises.map((e) => e.toMap()).toList();
  }

  /// Convert to GeneratedSessionData for compatibility with existing UI code
  GeneratedSessionData toSessionData({String? sessionId}) {
    return GeneratedSessionData(
      sessionId: sessionId,
      exercises: exercises.map((e) => e.toProgramExercise()).toList(),
      sessionDescription: sessionDescription,
      sessionDescriptionKo: sessionDescriptionKo,
    );
  }

  GeneratedSession copyWith({
    String? focusArea,
    TrainingSplit? trainingSplit,
    List<GeneratedExercise>? exercises,
    DateTime? generatedAt,
    String? sessionDescription,
    String? sessionDescriptionKo,
  }) {
    return GeneratedSession(
      focusArea: focusArea ?? this.focusArea,
      trainingSplit: trainingSplit ?? this.trainingSplit,
      exercises: exercises ?? this.exercises,
      generatedAt: generatedAt ?? this.generatedAt,
      sessionDescription: sessionDescription ?? this.sessionDescription,
      sessionDescriptionKo: sessionDescriptionKo ?? this.sessionDescriptionKo,
    );
  }
}

/// A single exercise with prescription parameters
/// Generated by rule-based algorithm
class GeneratedExercise {
  /// The exercise entity
  final ExerciseEntity exercise;

  /// Order in the session (0-indexed)
  final int orderIndex;

  /// Target number of sets
  final int targetSets;

  /// Target rep range (e.g., "8-12" or "10")
  final String targetReps;

  /// Target RPE (Rate of Perceived Exertion)
  final int targetRpe;

  /// Rest period in seconds
  final int restSeconds;

  /// Korean reasoning label for UI display (simple form)
  final String reasoningLabel;

  /// Detailed reasoning (optional, for expanded view)
  final String? reasoningDetail;

  const GeneratedExercise({
    required this.exercise,
    required this.orderIndex,
    required this.targetSets,
    required this.targetReps,
    required this.targetRpe,
    required this.restSeconds,
    required this.reasoningLabel,
    this.reasoningDetail,
  });

  /// Get exercise ID
  String get exerciseId => exercise.id;

  /// Get exercise name
  String get exerciseName => exercise.name;

  /// Get exercise display name (Korean if available)
  String get displayName => exercise.displayName;

  /// Convert to map for session creation
  Map<String, dynamic> toMap() {
    return {
      'exercise_id': exercise.id,
      'name': exercise.name,
      'name_ko': exercise.nameKo,
      'order_index': orderIndex,
      'target_sets': targetSets,
      'target_reps': targetReps,
      'target_rpe': targetRpe,
      'rest_seconds': restSeconds,
      'ai_reasoning': reasoningLabel,
      'ai_reasoning_ko': reasoningLabel,
    };
  }

  /// Convert to GeneratedProgramExercise for compatibility
  GeneratedProgramExercise toProgramExercise() {
    return GeneratedProgramExercise(
      exerciseId: exercise.id,
      name: exercise.name,
      nameKo: exercise.nameKo,
      orderIndex: orderIndex,
      targetSets: targetSets,
      targetReps: targetReps,
      restSeconds: restSeconds,
      aiReasoning: reasoningLabel,
      aiReasoningKo: reasoningLabel,
    );
  }

  GeneratedExercise copyWith({
    ExerciseEntity? exercise,
    int? orderIndex,
    int? targetSets,
    String? targetReps,
    int? targetRpe,
    int? restSeconds,
    String? reasoningLabel,
    String? reasoningDetail,
  }) {
    return GeneratedExercise(
      exercise: exercise ?? this.exercise,
      orderIndex: orderIndex ?? this.orderIndex,
      targetSets: targetSets ?? this.targetSets,
      targetReps: targetReps ?? this.targetReps,
      targetRpe: targetRpe ?? this.targetRpe,
      restSeconds: restSeconds ?? this.restSeconds,
      reasoningLabel: reasoningLabel ?? this.reasoningLabel,
      reasoningDetail: reasoningDetail ?? this.reasoningDetail,
    );
  }
}

/// Reasoning label constants (Korean)
class ReasoningLabels {
  static const String splitFocus = '오늘의 운동 포커스';
  static const String goalAlignment = '목표 달성에 효과적';
  static const String complementary = '이전 운동과 시너지';
  static const String focusArea = '집중 부위 타겟';
  static const String compoundPriority = '복합 운동 우선';
  static const String variety = '운동 다양성';
  static const String progressive = '점진적 발전';
  static const String balance = '근육 균형';
  static const String isolationFinisher = '마무리 단관절';
  static const String coreStability = '코어 안정성';

  /// Get label based on reason type
  static String getLabel(String reasonType) {
    switch (reasonType) {
      case 'split_focus':
        return splitFocus;
      case 'goal_alignment':
        return goalAlignment;
      case 'complementary':
        return complementary;
      case 'focus_area':
        return focusArea;
      case 'compound_priority':
        return compoundPriority;
      case 'variety':
        return variety;
      case 'progressive':
        return progressive;
      case 'balance':
        return balance;
      case 'isolation_finisher':
        return isolationFinisher;
      case 'core_stability':
        return coreStability;
      default:
        return goalAlignment;
    }
  }
}
