-- Populate ExerciseDB IDs and thumbnail URLs for exercises
-- This migration adds exercise images from the ExerciseDB API CDN
-- Run this via Supabase Dashboard SQL Editor

UPDATE exercises SET exercisedb_id = 'exr_41n2hWQVZanCB1d7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/TrP6PnRn1m.jpg' WHERE name = 'Arm Circle';
UPDATE exercises SET exercisedb_id = 'exr_41n2hMRXm49mM62z', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/L0IHjzfG7P.jpg' WHERE name = 'Arnold Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxnFMotsXTj3', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/A8OLBqBa26.jpg' WHERE name = 'Barbell Bench Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hGioS8HumEF7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/kCGgHyMFzA.jpg' WHERE name = 'Barbell Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdkBpqwoDmVq', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bXwXW2WUCj.jpg' WHERE name = 'Barbell Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hmGR8WuVfe1U', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/QBL8IYGdYK.jpg' WHERE name = 'Barbell Squat';
UPDATE exercises SET exercisedb_id = 'exr_41n2hmhb4jD7H8Qk', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/Tl37RFX06h.jpg' WHERE name = 'Bike';
UPDATE exercises SET exercisedb_id = 'exr_41n2hW9gDXAJJMmH', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/GpSc5Fff18.jpg' WHERE name = 'Bird Dog';
UPDATE exercises SET exercisedb_id = 'exr_41n2hN468sP27Sac', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/O0qDWx1dPm.jpg' WHERE name = 'Box Jump';
UPDATE exercises SET exercisedb_id = 'exr_41n2hpLLs1uU5atr', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/HLm5e1fMdO.jpg' WHERE name = 'Bulgarian Split Squat';
UPDATE exercises SET exercisedb_id = 'exr_41n2hqYdxG87hXz1', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/Df8GGoa6Yl.jpg' WHERE name = 'Burpee';
UPDATE exercises SET exercisedb_id = 'exr_41n2hskeb9dXgBoC', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/vCL0Cgs8A4.jpg' WHERE name = 'Cable Crunch';
UPDATE exercises SET exercisedb_id = 'exr_41n2hGioS8HumEF7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/kCGgHyMFzA.jpg' WHERE name = 'Cable Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hXszY7TgwKy4', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/S7KbaJxkei.jpg' WHERE name = 'Chin-Up';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxnFMotsXTj3', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/A8OLBqBa26.jpg' WHERE name = 'Close Grip Bench Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxqpSU5p6DZv', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/YXSxsv8zit.jpg' WHERE name = 'Concentration Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hskeb9dXgBoC', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/vCL0Cgs8A4.jpg' WHERE name = 'Crunch';
UPDATE exercises SET exercisedb_id = 'exr_41n2hn8rpbYihzEW', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/3wgSOkOkH5.jpg' WHERE name = 'Dead Bug';
UPDATE exercises SET exercisedb_id = 'exr_41n2hn8rpbYihzEW', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/3wgSOkOkH5.jpg' WHERE name = 'Deadlift';
UPDATE exercises SET exercisedb_id = 'exr_41n2hsVHu7B1MTdr', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/DhC4s2apCJ.jpg' WHERE name = 'Decline Bench Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hRZ6fgsLyd77', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/GQfzn89uwq.jpg' WHERE name = 'Diamond Push-Up';
UPDATE exercises SET exercisedb_id = 'exr_41n2hHH9bNfi98YU', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/mc56eseHDh.jpg' WHERE name = 'Dips';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxnFMotsXTj3', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/A8OLBqBa26.jpg' WHERE name = 'Dumbbell Bench Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hGioS8HumEF7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/kCGgHyMFzA.jpg' WHERE name = 'Dumbbell Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hyNf5GebszTf', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/6Ak3e2G7EC.jpg' WHERE name = 'Dumbbell Fly';
UPDATE exercises SET exercisedb_id = 'exr_41n2hn8rpbYihzEW', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/3wgSOkOkH5.jpg' WHERE name = 'Dumbbell RDL';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdkBpqwoDmVq', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bXwXW2WUCj.jpg' WHERE name = 'Dumbbell Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hVCJfpAvJcdU', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/tczafQq5N0.jpg' WHERE name = 'Face Pull';
UPDATE exercises SET exercisedb_id = 'exr_41n2hoyHUrhBiEWg', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/BhPdab2V0E.jpg' WHERE name = 'Farmers Walk';
UPDATE exercises SET exercisedb_id = 'exr_41n2howQHvcrcrW6', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/7ap5Us3CPK.jpg' WHERE name = 'Front Raise';
UPDATE exercises SET exercisedb_id = 'exr_41n2hQDiSwTZXM4F', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/lwT5fwjbAU.jpg' WHERE name = 'Front Squat';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxxePSdr5oN1', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/MpLOvIJHP1.jpg' WHERE name = 'Glute Bridge';
UPDATE exercises SET exercisedb_id = 'exr_41n2hQDiSwTZXM4F', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/lwT5fwjbAU.jpg' WHERE name = 'Goblet Squat';
UPDATE exercises SET exercisedb_id = 'exr_41n2hQDiSwTZXM4F', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/lwT5fwjbAU.jpg' WHERE name = 'Hack Squat';
UPDATE exercises SET exercisedb_id = 'exr_41n2hGioS8HumEF7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/kCGgHyMFzA.jpg' WHERE name = 'Hammer Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hMZCmZBvQApL', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/RAFQMtW2iL.jpg' WHERE name = 'Hanging Leg Raise';
UPDATE exercises SET exercisedb_id = 'exr_41n2hWQVZanCB1d7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/TrP6PnRn1m.jpg' WHERE name = 'Hip Circle';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxxePSdr5oN1', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/MpLOvIJHP1.jpg' WHERE name = 'Hip Thrust';
UPDATE exercises SET exercisedb_id = 'exr_41n2hsVHu7B1MTdr', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/DhC4s2apCJ.jpg' WHERE name = 'Incline Barbell Bench Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2haNJ3NA8yCE2', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/qkXo99D6UI.jpg' WHERE name = 'Incline Dumbbell Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2haNJ3NA8yCE2', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/qkXo99D6UI.jpg' WHERE name = 'Incline Dumbbell Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hN468sP27Sac', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/O0qDWx1dPm.jpg' WHERE name = 'Jump Rope';
UPDATE exercises SET exercisedb_id = 'exr_41n2hadPLLFRGvFk', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/9fW96RFqRZ.jpg' WHERE name = 'Lat Pulldown';
UPDATE exercises SET exercisedb_id = 'exr_41n2hjuGpcex14w7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/qODXfaAVcz.jpg' WHERE name = 'Lateral Raise';
UPDATE exercises SET exercisedb_id = 'exr_41n2hfYD2sH4TRCH', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/IAiYz72hHZ.jpg' WHERE name = 'Leg Extension';
UPDATE exercises SET exercisedb_id = 'exr_41n2hMRXm49mM62z', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/L0IHjzfG7P.jpg' WHERE name = 'Leg Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hbLX4XH8xgN7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bAEQLWIqH4.jpg' WHERE name = 'Leg Press Calf Raise';
UPDATE exercises SET exercisedb_id = 'exr_41n2hq3Wm6ANkgUz', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/URFCnmUsli.jpg' WHERE name = 'Lying Leg Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hxnFMotsXTj3', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/A8OLBqBa26.jpg' WHERE name = 'Machine Chest Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdkBpqwoDmVq', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bXwXW2WUCj.jpg' WHERE name = 'Machine Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hs6camM22yBG', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bQUAOjC7qA.jpg' WHERE name = 'Machine Shoulder Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdCBvmbCPaVE', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/6SPVwjalAc.jpg' WHERE name = 'Overhead Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdCBvmbCPaVE', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/6SPVwjalAc.jpg' WHERE name = 'Pallof Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hy8pKXtzuBh8', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/3tZIhVrazy.jpg' WHERE name = 'Plank';
UPDATE exercises SET exercisedb_id = 'exr_41n2hGioS8HumEF7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/kCGgHyMFzA.jpg' WHERE name = 'Preacher Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hsBtDXapcADg', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/g0ZmaTcu2Q.jpg' WHERE name = 'Pull-Up';
UPDATE exercises SET exercisedb_id = 'exr_41n2hNXJadYcfjnd', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/cuG10rd4ea.jpg' WHERE name = 'Push-Up';
UPDATE exercises SET exercisedb_id = 'exr_41n2hyNf5GebszTf', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/6Ak3e2G7EC.jpg' WHERE name = 'Rear Delt Fly';
UPDATE exercises SET exercisedb_id = 'exr_41n2hn8rpbYihzEW', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/3wgSOkOkH5.jpg' WHERE name = 'Romanian Deadlift';
UPDATE exercises SET exercisedb_id = 'exr_41n2hWVVEwU54UtF', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/Z50HKjVbLP.jpg' WHERE name = 'Russian Twist';
UPDATE exercises SET exercisedb_id = 'exr_41n2hhiWL8njJDZe', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/9TeNhxGH3F.jpg' WHERE name = 'Seated Cable Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hTs4q3ihihZs', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/4TWa5X9NV0.jpg' WHERE name = 'Seated Calf Raise';
UPDATE exercises SET exercisedb_id = 'exr_41n2hs6camM22yBG', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bQUAOjC7qA.jpg' WHERE name = 'Seated Dumbbell Press';
UPDATE exercises SET exercisedb_id = 'exr_41n2hu5r8WMaLUkH', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/lnyRErycIc.jpg' WHERE name = 'Seated Leg Curl';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdHtZrMPkcqY', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/LqKaE2JobC.jpg' WHERE name = 'Skull Crusher';
UPDATE exercises SET exercisedb_id = 'exr_41n2ha5iPFpN3hEJ', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/EsVOYBdhDN.jpg' WHERE name = 'Stair Climber';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdWu3oaCGdWT', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/RfXMrjCG6o.jpg' WHERE name = 'Standing Calf Raise';
UPDATE exercises SET exercisedb_id = 'exr_41n2hcw2FN534HcA', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/1aHXOCzatq.jpg' WHERE name = 'Stiff Leg Deadlift';
UPDATE exercises SET exercisedb_id = 'exr_41n2hWxnJoGwbJpa', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/ixufDWekVb.jpg' WHERE name = 'T-Bar Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hjkBReJMbDJk', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/t8EmH7ry7L.jpg' WHERE name = 'Treadmill Running';
UPDATE exercises SET exercisedb_id = 'exr_41n2hHH9bNfi98YU', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/mc56eseHDh.jpg' WHERE name = 'Tricep Kickback';
UPDATE exercises SET exercisedb_id = 'exr_41n2hPgRbN1KtJuD', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bJE2dLg62R.jpg' WHERE name = 'Tricep Pushdown';
UPDATE exercises SET exercisedb_id = 'exr_41n2hdo2vCtq4F3E', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/NenhkXpa3a.jpg' WHERE name = 'Upright Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hQHmRSoUkk9F', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/g2s9vxBfWN.jpg' WHERE name = 'Walking Lunge';
UPDATE exercises SET exercisedb_id = 'exr_41n2hftBVLiXgtRQ', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/KTxTtuwOqD.jpg' WHERE name = 'Wide Grip Lat Pulldown';
UPDATE exercises SET exercisedb_id = 'exr_41n2hPgRbN1KtJuD', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bJE2dLg62R.jpg' WHERE name = 'Close Grip Lat Pulldown';
UPDATE exercises SET exercisedb_id = 'exr_41n2hRicz5MdZEns', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/st1x4DMne6.jpg' WHERE name = 'Cable Pull Through';
UPDATE exercises SET exercisedb_id = 'exr_41n2hpDWoTxocW8G', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/9wu5xHWC5e.jpg' WHERE name = 'Cable Crossover';
UPDATE exercises SET exercisedb_id = 'exr_41n2hpTMDhTxYkvi', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/tgjIfyDnSH.jpg' WHERE name = 'Pec Deck Machine';
UPDATE exercises SET exercisedb_id = 'exr_41n2hpTMDhTxYkvi', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/tgjIfyDnSH.jpg' WHERE name = 'Smith Machine Squat';
UPDATE exercises SET exercisedb_id = 'exr_41n2hushK9NGVfyK', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/qzcFGKedZz.jpg' WHERE name = 'Assisted Pull-Up';
UPDATE exercises SET exercisedb_id = 'exr_41n2hSkc2tRLxVVS', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/qbphLBTjbs.jpg' WHERE name = 'Battle Ropes';
UPDATE exercises SET exercisedb_id = 'exr_41n2hcm5HH6H684G', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/po63VThsX2.jpg' WHERE name = 'Chest Supported Row';
UPDATE exercises SET exercisedb_id = 'exr_41n2hwio5ECAfLuS', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/NsGBTPFcDo.jpg' WHERE name = 'Good Morning';
UPDATE exercises SET exercisedb_id = 'exr_41n2hzAMXkkQQ5T2', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/bQqmNEEdBJ.jpg' WHERE name = 'Overhead Carry';
UPDATE exercises SET exercisedb_id = 'exr_41n2hn2kPMag9WCf', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/iqDuGsnDUE.jpg' WHERE name = 'Overhead Tricep Extension';
UPDATE exercises SET exercisedb_id = 'exr_41n2hTaeNKWhMQHH', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/Hi7uCOg9S1.jpg' WHERE name = 'Suitcase Carry';
UPDATE exercises SET exercisedb_id = 'exr_41n2hTaeNKWhMQHH', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/Hi7uCOg9S1.jpg' WHERE name = 'Trap Bar Carry';
UPDATE exercises SET exercisedb_id = 'exr_41n2hTCBiQVsEfZ7', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/8WIXy0XUL3.jpg' WHERE name = 'Foam Roll';
UPDATE exercises SET exercisedb_id = 'exr_41n2hGNrmUnF58Yy', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/XUs62RE49n.jpg' WHERE name = 'Cat-Cow';
UPDATE exercises SET exercisedb_id = 'exr_41n2hbYPY4jLKxW3', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/AcGb20UoJg.jpg' WHERE name = 'World Greatest Stretch';
UPDATE exercises SET exercisedb_id = 'exr_41n2howQHvcrcrW6', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/7ap5Us3CPK.jpg' WHERE name = 'Rowing Machine';
UPDATE exercises SET exercisedb_id = 'exr_41n2hqYdxG87hXz1', thumbnail_url = 'https://cdn.exercisedb.dev/media/w/images/Df8GGoa6Yl.jpg' WHERE name = 'Ab Wheel Rollout';
