// generate-pdf Edge Function
// Generates PDF workout reports using jsPDF

import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface ReportData {
  sessionId: string
  clientName: string
  trainerName: string
  sessionDate: string
  duration: number // in minutes
  exercises: ExerciseData[]
  highlights: Highlight[]
  trainerNotes?: string
  stats: SessionStats
}

interface ExerciseData {
  name: string
  muscleGroup?: string
  sets: SetData[]
  totalVolume: number
}

interface SetData {
  setNumber: number
  weight: number
  reps: number
  rpe?: number
  isPR?: boolean
}

interface Highlight {
  type: 'pr' | 'volume' | 'consistency' | 'improvement'
  title: string
  description: string
}

interface SessionStats {
  totalSets: number
  totalReps: number
  totalVolume: number
  exerciseCount: number
  avgRpe?: number
}

// Simple PDF generation using text-based approach
// For more complex PDFs, consider using @pdfme/generator or similar
function generatePdfContent(data: ReportData): Uint8Array {
  // Create PDF content as text (simplified version)
  // In production, you'd use a proper PDF library like jsPDF or PDFKit

  const pdfLines: string[] = []

  // PDF Header
  pdfLines.push('%PDF-1.4')
  pdfLines.push('1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj')
  pdfLines.push('2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj')

  // Build content string
  const content = buildReportContent(data)

  // Page object with content
  pdfLines.push(`3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj`)

  // Content stream
  const contentStream = buildContentStream(content)
  pdfLines.push(`4 0 obj << /Length ${contentStream.length} >> stream`)
  pdfLines.push(contentStream)
  pdfLines.push('endstream endobj')

  // Font
  pdfLines.push('5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj')

  // Cross-reference table
  pdfLines.push('xref')
  pdfLines.push('0 6')
  pdfLines.push('0000000000 65535 f ')
  pdfLines.push('0000000009 00000 n ')
  pdfLines.push('0000000058 00000 n ')
  pdfLines.push('0000000115 00000 n ')
  pdfLines.push('0000000270 00000 n ')
  pdfLines.push('0000000380 00000 n ')

  // Trailer
  pdfLines.push('trailer << /Size 6 /Root 1 0 R >>')
  pdfLines.push('startxref')
  pdfLines.push('456')
  pdfLines.push('%%EOF')

  const pdfContent = pdfLines.join('\n')
  return new TextEncoder().encode(pdfContent)
}

function buildReportContent(data: ReportData): string[] {
  const lines: string[] = []

  // Header
  lines.push('FITLOG PRO - WORKOUT REPORT')
  lines.push('')
  lines.push(`Client: ${data.clientName}`)
  lines.push(`Trainer: ${data.trainerName}`)
  lines.push(`Date: ${data.sessionDate}`)
  lines.push(`Duration: ${data.duration} minutes`)
  lines.push('')

  // Highlights
  if (data.highlights.length > 0) {
    lines.push('--- HIGHLIGHTS ---')
    for (const highlight of data.highlights) {
      lines.push(`[${highlight.type.toUpperCase()}] ${highlight.title}`)
      lines.push(`  ${highlight.description}`)
    }
    lines.push('')
  }

  // Exercises
  lines.push('--- EXERCISES ---')
  for (const exercise of data.exercises) {
    lines.push('')
    lines.push(`${exercise.name} (${exercise.muscleGroup || 'General'})`)
    lines.push(`Total Volume: ${exercise.totalVolume} kg`)

    for (const set of exercise.sets) {
      const prMarker = set.isPR ? ' [PR!]' : ''
      const rpeStr = set.rpe ? ` RPE ${set.rpe}` : ''
      lines.push(`  Set ${set.setNumber}: ${set.weight}kg x ${set.reps}${rpeStr}${prMarker}`)
    }
  }
  lines.push('')

  // Stats
  lines.push('--- SESSION STATS ---')
  lines.push(`Total Sets: ${data.stats.totalSets}`)
  lines.push(`Total Reps: ${data.stats.totalReps}`)
  lines.push(`Total Volume: ${data.stats.totalVolume} kg`)
  lines.push(`Exercises: ${data.stats.exerciseCount}`)
  if (data.stats.avgRpe) {
    lines.push(`Average RPE: ${data.stats.avgRpe.toFixed(1)}`)
  }

  // Trainer notes
  if (data.trainerNotes) {
    lines.push('')
    lines.push('--- TRAINER NOTES ---')
    lines.push(data.trainerNotes)
  }

  lines.push('')
  lines.push('Generated by FitLog Pro')

  return lines
}

function buildContentStream(lines: string[]): string {
  const operations: string[] = []
  operations.push('BT')
  operations.push('/F1 12 Tf')

  let y = 750
  for (const line of lines) {
    if (line.startsWith('---')) {
      // Section header
      operations.push('/F1 14 Tf')
      operations.push(`50 ${y} Td`)
      operations.push(`(${escapePdfString(line)}) Tj`)
      operations.push('/F1 12 Tf')
    } else if (line === 'FITLOG PRO - WORKOUT REPORT') {
      // Main title
      operations.push('/F1 18 Tf')
      operations.push(`50 ${y} Td`)
      operations.push(`(${escapePdfString(line)}) Tj`)
      operations.push('/F1 12 Tf')
    } else {
      operations.push(`50 ${y} Td`)
      operations.push(`(${escapePdfString(line)}) Tj`)
    }
    y -= 15

    // New page if needed
    if (y < 50) {
      y = 750
    }
  }

  operations.push('ET')
  return operations.join('\n')
}

function escapePdfString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

serve(async (req) => {
  // Handle CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    const supabase = createClient(supabaseUrl, supabaseKey)

    const { sessionId, trainerNotes } = await req.json()

    if (!sessionId) {
      return new Response(
        JSON.stringify({ error: 'Session ID is required' }),
        {
          status: 400,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      )
    }

    // Fetch session data
    const { data: session, error: sessionError } = await supabase
      .from('sessions')
      .select(`
        *,
        client:accounts!sessions_client_id_fkey(full_name),
        trainer:accounts!sessions_trainer_id_fkey(full_name),
        session_exercises(
          *,
          exercise:exercises(*),
          exercise_sets(*)
        )
      `)
      .eq('id', sessionId)
      .single()

    if (sessionError || !session) {
      return new Response(
        JSON.stringify({ error: 'Session not found' }),
        {
          status: 404,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      )
    }

    // Calculate session stats and build report data
    const exercises: ExerciseData[] = []
    let totalSets = 0
    let totalReps = 0
    let totalVolume = 0
    let rpeSum = 0
    let rpeCount = 0
    const highlights: Highlight[] = []

    for (const sessionExercise of session.session_exercises) {
      const sets: SetData[] = []
      let exerciseVolume = 0

      for (const set of sessionExercise.exercise_sets) {
        const volume = set.weight * set.reps
        exerciseVolume += volume
        totalVolume += volume
        totalSets++
        totalReps += set.reps

        if (set.rpe) {
          rpeSum += set.rpe
          rpeCount++
        }

        sets.push({
          setNumber: set.set_number,
          weight: set.weight,
          reps: set.reps,
          rpe: set.rpe,
          isPR: set.is_pr || false,
        })

        // Check for PR highlights
        if (set.is_pr) {
          highlights.push({
            type: 'pr',
            title: `New PR: ${sessionExercise.exercise.name}`,
            description: `${set.weight}kg x ${set.reps} reps`,
          })
        }
      }

      exercises.push({
        name: sessionExercise.exercise.name,
        muscleGroup: sessionExercise.exercise.muscle_group,
        sets,
        totalVolume: exerciseVolume,
      })
    }

    // Add volume highlight if high
    if (totalVolume > 5000) {
      highlights.push({
        type: 'volume',
        title: 'High Volume Session',
        description: `${totalVolume.toLocaleString()} kg total volume`,
      })
    }

    const sessionDate = new Date(session.started_at).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })

    const duration = session.completed_at && session.started_at
      ? Math.round((new Date(session.completed_at).getTime() - new Date(session.started_at).getTime()) / 60000)
      : 0

    const reportData: ReportData = {
      sessionId,
      clientName: session.client?.full_name || 'Unknown Client',
      trainerName: session.trainer?.full_name || 'Unknown Trainer',
      sessionDate,
      duration,
      exercises,
      highlights,
      trainerNotes,
      stats: {
        totalSets,
        totalReps,
        totalVolume,
        exerciseCount: exercises.length,
        avgRpe: rpeCount > 0 ? rpeSum / rpeCount : undefined,
      },
    }

    // Generate PDF
    const pdfContent = generatePdfContent(reportData)

    // Upload PDF to Supabase Storage
    const fileName = `reports/${sessionId}_${Date.now()}.pdf`
    const { data: uploadData, error: uploadError } = await supabase
      .storage
      .from('session-reports')
      .upload(fileName, pdfContent, {
        contentType: 'application/pdf',
        upsert: true,
      })

    if (uploadError) {
      console.error('Upload error:', uploadError)
      return new Response(
        JSON.stringify({ error: 'Failed to upload PDF' }),
        {
          status: 500,
          headers: { ...corsHeaders, 'Content-Type': 'application/json' }
        }
      )
    }

    // Get public URL
    const { data: urlData } = supabase
      .storage
      .from('session-reports')
      .getPublicUrl(fileName)

    // Update session_reports table with PDF URL
    await supabase
      .from('session_reports')
      .upsert({
        session_id: sessionId,
        pdf_url: urlData.publicUrl,
        generated_at: new Date().toISOString(),
      })

    return new Response(
      JSON.stringify({
        success: true,
        pdfUrl: urlData.publicUrl,
        reportData: {
          highlights: reportData.highlights,
          stats: reportData.stats,
        },
      }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    )

  } catch (error) {
    console.error('Error generating PDF:', error)
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' }
      }
    )
  }
})
